### ISSUE TITLE
Terraform Options Submission Loading Animation

### ISSUE THREAD

**Issue by chrispetrone** [devxp-ca/devxp#200] opened 2022-03-17 17:53 UTC
Something like https://mui.com/components/progress/ ,

Likely best to use an indeterminate loading animation.  possible we could stack a linear one over the modal so it looks like its part of it.

- [ ] State management to track submission, response
- [ ] Positioning over modal or overlay on screen

**Comment by keanelekenns** [comment] 2022-03-19 04:42
Is this a duplicate of #184 ?

**Comment by keanelekenns** [comment] 2022-03-19 04:43
Maybe you could put the extra details of this there and close this if so?

**Closed** 2022-03-29 06:45 UTC
Labels: duplicate, nice to have
